### PR TITLE
Update slide randyb

### PR DESCRIPTION
**Pull request by randyb77**
Please review updated slide

### CODE REVIEW

**Comment by CarmenFerretti** [comment]
Hello!

**Comment by randyb77** [comment]
Yeah, we have done this before, right?

**Comment by CarmenFerretti** [comment]
Yeap!

**Comment by randyb77** [comment]
Can you approve this?

**Comment by CarmenFerretti** [comment]
Approved

**Review by randyb77 — COMMENTED** [review]
@CarmenFerretti you have to go to my changes and under "Review Changes" select Approve.

**Review by CarmenFerretti — APPROVED** [review]

**Pull request merged**
